### ISSUE TITLE
feature request: 捕获下载的监视和例外列表可以批量禁用和启用

### ISSUE THREAD

**Issue by ivysrono** [jc3213/download_with_aria2#100]
现在是要么进入列表，要么移除出列表，不利于测试维护。

希望能每条规则有个checkbox来选择启用或禁用。

最好还能有个一键禁用/启用全部规则的开关。

**Comment by jc3213** [comment]
这个还要增加额外储存来记录状态……虽然不是不可以做，但是感觉真没必要吧？你可以通过`Ctrl+Z`撤销之前的操作。

**Comment by jc3213** [comment]
我优化了一下删除，添加规则的逻辑，这样不会每次`撤销`跟`恢复`后都重新刷新删除所有元素并且重新制作了。能省不少性能。
