### ISSUE TITLE
2792error

### ISSUE THREAD

**Issue by ivysrono** [jc3213/download_with_aria2#101]
JavaScript syntax error (Parsing as module error: Unexpected token } at line: 50 and column: 2) (Parsing as script error: Unexpected token } at line: 50 and column: 2)

Error: There is a JavaScript syntax error in your code, which might be related to some experimental JavaScript features that aren't an official part of the language specification and therefore not supported yet. The validation cannot continue on this file.
pages/newdld/newdld.js line 50 column 2

**Comment by jc3213** [comment]
看到了，是打错了，昨天突然鼻炎发作没睡好，今天急着修bug导致的，最新版已经修复了。

**Comment by jc3213** [comment]
发现昨天改的代码也有点问题——`Import`，即`导入`设置功能抽风了，2795已经修复了。

理论上应该没什么问题了，如果发现问题欢迎反馈。如果没大问题的话在想到啥新东西之前估计不会碰这个扩展了。

我准备回头把[Easy Proxy](https://github.com/jc3213/easy_proxy)的列表管理界面做成这个扩展这样，然后再优化一下行为逻辑啥的。虽然目前这样已经足够我自己日常使用就是了。
