### ISSUE TITLE
not capturing downloads anymore

### ISSUE THREAD

**Issue by procopaeus** [jc3213/download_with_aria2#102]
as of some 2 weeks to today, your addon for firefox is not capturing any downloads for me, I didn't change any settings in the addon. i don't use your [batchscript for aria2c](https://github.com/jc3213/batchscript/tree/main/aria2c) to start aria2c because is has the most unclear instructions ever of any code and never worked for me. instead I always used [another one](https://github.com/saaiful/aria2-win64-rpc) with a .vbs file that's simple and worked with your addon and still works with [Aria2 Explorer](https://chromewebstore.google.com/detail/aria2-explorer/mpkodccbngfoacfalldjimigbofkhgjn) for Chrome and it captures downloads normally. sorry but I'm being sincere and hope you could explain what's happening.

**Comment by jc3213** [comment]
As mentioned in https://github.com/jc3213/download_with_aria2/issues/99#issuecomment-2284001424 You can add `*` to `Include Hosts` to do the same as `Always Capture Downloads` which has been removed in latest release
