### ISSUE TITLE
[FR]: 如果没有连接到aria2则不捕获下载？

### ISSUE THREAD

**Issue by detiam** [jc3213/download_with_aria2#103]
现在只要扩展开着就会尝试捕获，就算aria2没连上，结果就是什么都没有下载
只是开一下浏览器下小文件不太方便，没连上aria2就暂停捕获是不是比较好呢

**Comment by jc3213** [comment]
我在考虑怎么实现这个功能，目前因为`aria2.js`中定义了中断就尝试重连，我设置了无数次，回头我把这个次数单独提取出来做个选项。然后再把中断的判断逻辑写进去，然后定义中断时的事件。最后回到这里，我在移除事件监听器，跟单独添加个条件判断之间纠结。理论上移除事件监听器性能会更好，但是如果反复开关aria2导致反复注册，移除事件监听器的话可能会出问题。毕竟js不怎么可靠
