### ISSUE TITLE
能不能增加分类

### ISSUE THREAD

**Issue by paulxjz** [jc3213/download_with_aria2#104]
如题，就是可以设置几个常用文件夹，下载的时候同类的文件就自动下到同一个文件夹。例如，压缩文件就全部放一个文件夹，视频就都放在一个文件夹，最好可以自定义关键词或后缀名。

**Comment by jc3213** [comment]
理论上是可以实现的，不过我暂时不考虑加入这个功能。目前看来就`抓取浏览器下载`这个功能能跟你的要求正相关。而使用上下文菜单，以及通过[Wiki:Message](https://github.com/jc3213/download_with_aria2/wiki/Message)添加的下载进行处理时，默认是不存在请求头跟相关内容的，也就是必须手动获取通过`fetch` API来获取（mv3不存在xmlhttprequest），这个过程会带来操作延迟，并且不一定能正确的获取到相关内容。

我这边只能操作浏览器请求，对aria2的管理停留在json-rpc这个范围，而你的要求从aria2端实现更靠谱一点。

**Comment by zeromake** [comment]
有点意思，考虑在我的 [fork](https://github.com/zeromake/aria2-zero) 里实现
大概就是：
```
category-sub-dir=.tar.xz:压缩包,.txt:文本
```
现在考虑的是要用正则还是简单的后缀匹配

**Comment by jc3213** [comment]
> ```
> category-sub-dir=.tar.xz:压缩包,.txt:文本
> ```
我觉得用`;`做分隔符比,更直观点吧？然后如果多个后缀放入同一个文件夹，比如`.zip,.rar:压缩包;`这样反而更直观

**Comment by zeromake** [comment]
@jc3213 
挺好的，不过我建议 `@` 换成 `:` 因为 `@` 在 windows 里可以作为文件名而 `:` 不行，`category-sub-dir` 感觉有点长改为 `category-dir` ，aria2 的多行 option 实际上就是用 `\n` 连接起来了，我就做成 `.zip,.rar:压缩包;.jpg,.png:图片;` 与 `.zip,.rar:压缩包\n.jpg,.png:图片\n` 兼容了

**Comment by jc3213** [comment]
很不错，目前aria2主repo没相关的功能，从浏览器扩展来实现这个功能太不方便了而且不切实际了。

@paulxjz 你可以关注下[zeromake的aria2分支repo](https://github.com/zeromake/aria2-zero)

**Comment by paulxjz** [comment]
> 很不错，目前aria2主repo没相关的功能，从浏览器扩展来实现这个功能太不方便了而且不切实际了。
> 
> @paulxjz 你可以关注下[zeromake的aria2分支repo](https://github.com/zeromake/aria2-zero)

ok,我关注下

**Comment by jc3213** [comment]
> @jc3213 挺好的，不过我建议 `@` 换成 `:` 因为 `@` 在 windows 里可以作为文件名而 `:` 不行，`category-sub-dir` 感觉有点长改为 `category-dir` ，aria2 的多行 option 实际上就是用 `\n` 连接起来了，我就做成 `.zip,.rar:压缩包;.jpg,.png:图片;` 与 `.zip,.rar:压缩包\n.jpg,.png:图片\n` 兼容了

我突然想起来，Windows批处理中,也是按照空格算的。除非用`“a,b”`进行处理，我那个提议好像真有点问题。

**Comment by zeromake** [comment]
@jc3213 @paulxjz 
加好了:
https://github.com/zeromake/aria2-zero/releases/tag/v2024.12.28-release.1
有些限制可以去看看：
https://github.com/zeromake/aria2-zero/pull/6

**Comment by paulxjz** [comment]
> @jc3213 @paulxjz 加好了: https://github.com/zeromake/aria2-zero/releases/tag/v2024.12.28-release.1 有些限制可以去看看： [zeromake/aria2-zero#6](https://github.com/zeromake/aria2-zero/pull/6)

我用了下，感觉还是不错的，就是我使用场景最多是，在浏览器拦截下载链接，这个场景不能使用分类，如果是自己添加下载链接是正常分类的

**Comment by jc3213** [comment]
> > @jc3213 @paulxjz 加好了: https://github.com/zeromake/aria2-zero/releases/tag/v2024.12.28-release.1 有些限制可以去看看： [zeromake/aria2-zero#6](https://github.com/zeromake/aria2-zero/pull/6)
> 
> 我用了下，感觉还是不错的，就是我使用场景最多是，在浏览器拦截下载链接，这个场景不能使用分类，如果是自己添加下载链接是正常分类的

因为抓取下载时会根据提供的filename进行文件名的提取然后获取文件名，在进行 `{ out : "文件名" }` 的设置，这个跟 @zeromake 的设置冲突了。但是不这么做一些下载文件名会出现%5B之类的占位符

**Comment by zeromake** [comment]
> > > @jc3213 @paulxjz 加好了: https://github.com/zeromake/aria2-zero/releases/tag/v2024.12.28-release.1 有些限制可以去看看： [zeromake/aria2-zero#6](https://github.com/zeromake/aria2-zero/pull/6)
> > 
> > 
> > 我用了下，感觉还是不错的，就是我使用场景最多是，在浏览器拦截下载链接，这个场景不能使用分类，如果是自己添加下载链接是正常分类的
> 
> 因为抓取下载时会根据提供的`downloadItem.filename`进行文件名的提取然后获取文件名，在进行 `{ out : "文件名" }` 的设置，这个跟 @zeromake 的设置冲突了。但是不这么做一些下载文件名会出现%5B之类的占位符
> 
> @zeromake 请问为什么 `-o` 或 `-out` 会跟你的修改冲突？如果是考虑到 `-o` 提供相对路径的话你可以考虑直接提取最后的文件名？例如 ` { out: "/somedir/somename.ext" }` 你可以直接提取 `somename.ext` 然后适配上面的操作。

冲突的原因不是技术问题，是逻辑上的，我这边考虑的问题是 `-o` 在来自用户指定路径的情况下依旧进行自动分组可能会违背了用户自定义下载路径的意思，可以考虑再加一个参数让 `category-dir` 对 `-o` 的情况也生效？

还有自动命名不能正常转义 `%5B` 应该算是一个 bug，我有空修一下，有示例 url 吗？

**Comment by zeromake** [comment]
我加了一个 `--category-dir-scope` 控制应用范围
1: 就是默认范围，对 http, ftp, sftp 的自动命名生效
2: 对命令行和远端传递的 `out` 选项生效
一般来说直接在配置里设置为 `category-dir-scope=3` 就可以了
https://github.com/zeromake/aria2-zero/pull/7

**Comment by jc3213** [comment]
> 冲突的原因不是技术问题，是逻辑上的，我这边考虑的问题是 `-o` 在来自用户指定路径的情况下依旧进行自动分组可能会违背了用户自定义下载路径的意思，可以考虑再加一个参数让 `category-dir` 对 `-o` 的情况也生效？
> 我加了一个 --category-dir-scope 控制应用范围
能解决就很好

> 还有自动命名不能正常转义 `%5B` 应该算是一个 bug，我有空修一下，有示例 url 吗？
这个是很早之前的bug了，这个repo也是整合了火狐跟chromium代码的新repo，之前的老repo我已经删除掉了。我记得是只要默认的文件名带类似`<>`这种特殊符号，类似`www.abc.com/some <my> test.zip`这种地址格式就会出现。当时我记得还是aria2 1.24版本。

**Comment by paulxjz** [comment]
> 我加了一个 `--category-dir-scope` 控制应用范围 1: 就是默认范围，对 http, ftp, sftp 的自动命名生效 2: 对命令行和远端传递的 `out` 选项生效 一般来说直接在配置里设置为 `category-dir-scope=3` 就可以了 [zeromake/aria2-zero#7](https://github.com/zeromake/aria2-zero/pull/7)
> 
> 最新包请到 https://github.com/zeromake/aria2-zero/releases/tag/v2024.12.29-release.1

我用了v2024.12.29-release.1，好像还是不行，在浏览器拦截下载链接，还是不能分类

**Comment by zeromake** [comment]
@paulxjz 我只测试了命令行的，可能是rpc的路径设置没改，我有空看看吧

**Comment by zeromake** [comment]
@paulxjz 
```sh
curl -OL https://github.com/zeromake/aria2-zero/releases/download/v2024.12.29-release.1/aria2c-windows-x64.exe
./aria2c-windows-x64.exe --category-dir='程序:.exe;网页:.html;' --category-dir-scope=3 --enable-rpc=true --rpc-allow-origin-all
```
我测试了是正常生效的，不会没加 --category-dir-scope=3 吧……
手动通过 curl 和 download_with_aria2 都是正常生效：
```sh
curl --request POST \
  --url http://localhost:6800/jsonrpc \
  --header 'content-type: application/json' \
  --data '{
  "jsonrpc": "2.0",
  "method": "aria2.addUri",
  "id": "1",
  "params": [
    [
      "https://github.com/zeromake/aria2-zero/releases/download/v2024.12.29-release.1/aria2c-windows-x86.exe"
    ],
    {
      "out": "aria2c-windows-x86.exe"
    }
  ]
}'
```

```sh
[#59fb84 0B/0B CN:1 DL:0B]
FILE: D:/project/aria2-zero/程序/aria2c-windows-x86.exe
```

**Comment by paulxjz** [comment]
> @paulxjz
> 
> ```shell
> curl -OL https://github.com/zeromake/aria2-zero/releases/download/v2024.12.29-release.1/aria2c-windows-x64.exe
> ./aria2c-windows-x64.exe --category-dir='程序:.exe;网页:.html;' --category-dir-scope=3 --enable-rpc=true --rpc-allow-origin-all
> ```
> 
> 我测试了是正常生效的，不会没加 --category-dir-scope=3 吧…… 手动通过 curl 和 download_with_aria2 都是正常生效：
> 
> ```shell
> curl --request POST \
>   --url http://localhost:6800/jsonrpc \
>   --header 'content-type: application/json' \
>   --data '{
>   "jsonrpc": "2.0",
>   "method": "aria2.addUri",
>   "id": "1",
>   "params": [
>     [
>       "https://github.com/zeromake/aria2-zero/releases/download/v2024.12.29-release.1/aria2c-windows-x86.exe"
>     ],
>     {
>       "out": "aria2c-windows-x86.exe"
>     }
>   ]
> }'
> ```
> 
> ```shell
> [#59fb84 0B/0B CN:1 DL:0B]
> FILE: D:/project/aria2-zero/程序/aria2c-windows-x86.exe
> ```

确实没有加，应该是忘了保存了，现在可以了，感谢
