### ISSUE TITLE
why Capture downloads not working in firefox?

### ISSUE THREAD

**Issue by candrapersada** [jc3213/download_with_aria2#105]
why Capture browser downloads not working in firefox?
1. Download with Aria2 4.12.0.2970
2. Firefox 133.0.3

**Comment by jc3213** [comment]
You must add `*` to **Inculde Domains**

**Comment by candrapersada** [comment]
> You must add `*` to **Inculde Domains**

yes working but why use `*` to **Inculde Domains**?

**Comment by jc3213** [comment]
Yes, there was once a `Always Capture Downloads` checkbox in options, and has been deprecated since [4.11.0.2795](https://github.com/jc3213/download_with_aria2/releases/tag/4.11.0.2795)
