### ISSUE TITLE
Keep-Alive Service Worker [Manifest V3]

### ISSUE THREAD

**Issue by jc3213** [jc3213/download_with_aria2#11]
I've done the code with `Web Socket` for indicating aria2 running status. It works well for `Firefox` using background page, but can't work for Chromium due to the life time of `Service Worker`.

I wonder if someone can help me with this

_Originally posted by @jc3213 in https://github.com/jc3213/download_with_aria2/issues/10#issuecomment-1021149859_

**Comment by daiaji** [comment]
RPC那里直接填wss://aria2.test.xyz:8888/jsonrpc
就完事了？
好像没用。
还是WebSocket （safe）没实现？

**Comment by jc3213** [comment]
填写http，内部会自动转换成ws。因为更多的时候是本地用。wss协议我不是特别理解，跟https差不多需要证书么？
