### ISSUE TITLE
Multi Profile Manager | 多档案切换功能 基于[3.12.1]

### ISSUE THREAD

**Issue by jc3213** [jc3213/download_with_aria2#18]
## 主要功能
- English
    - Profiles management only on `Options`
        - Please `Save` if you have made any changes to current profile
    - Profile Name limited to `16` characters
    - Since `confirm` window is required, it will close `Popup` in `Chromium`
- 中文
    - 管理档案功能需要打开设置
        - 修改档案后需要点击`保存`，否则所有修改都将作废
    - 档案名仅限16字符长度（推荐使用英文字符，数字）
    - 需要用到`confirm`确认窗口，`Chromium`版本会自动关闭`Popup`

## 下载
[Source code](https://github.com/jc3213/download_with_aria2/archive/refs/heads/deluxe.zip)

## 分支
[Branch](https://github.com/jc3213/download_with_aria2/tree/deluxe)

## 修改点
[Changes](https://github.com/jc3213/download_with_aria2/compare/main...deluxe)

## 截图
![Default](https://user-images.githubusercontent.com/8744936/152557205-42cb1801-fa5c-4d1c-a73e-fe1dc6803bc2.png)
![Create New](https://user-images.githubusercontent.com/8744936/152557219-ebf39cf2-2ab9-499b-919a-695363ad6fef.png)
![popup](https://user-images.githubusercontent.com/8744936/153712160-4121aed4-d0f2-403e-8dd3-b1aabbba633a.png)

**Comment by jc3213** [comment]
@daiaji 你试试看最新的测试版，我目前只做了档案的新建，删除，设置为默认。右键菜单反而寸步难行。因为有弹出`confirm`确认窗口，必须在`about:addons`窗口下才能运行。

**Comment by jc3213** [comment]
@ivysrono 如果不介意的话你也可以帮忙测试一下。就是这个功能很初步，只能在需要的时候切换。虽然比复制粘贴JSON-RPC的信息方便点点……

**Comment by daiaji** [comment]
没看见这功能……

**Comment by jc3213** [comment]
你确定是从这个issue下载的源码？

**Comment by daiaji** [comment]
分支……，那没事了。

**Comment by jc3213** [comment]
> 分支……，那没事了。
没人测试，给反馈我不知道这个效果如何……后续怎么修改啥的，还是推到重来？我当初是没有往这方面预期，所以重写的时候很多东西都要重新弄

**Comment by daiaji** [comment]
显示有问题，捕获了链接会显示用得默认RPC。

**Comment by ivysrono** [comment]
这两天都在外没空测试……

**Comment by daiaji** [comment]
右键发送链接直接显示RPC1 RPC2就完事了吧。aria2-integration也是这么弄的，加个按键捕获怎么样？
万一aria2下不了，临时按住按键，然后点链接用浏览器自带的下载器下载。

**Comment by jc3213** [comment]
> 显示有问题，捕获了链接会显示用的默认RPC。

现在右键菜单跟抓取下载都是默认，你只有修改默认档案后才会变化……（仅限设置里）

> 万一aria2下不了，临时按住按键，然后点链接用浏览器自带的下载器下载。

这个实现不了，不管用哪个API，因为内容跟后台交互的问题。

> 右键发送链接，直接次级菜单显示RPC1 RPC2就完事了吧。

因为底层代码的问题，你看下background就知道了……，这里要大改，只是小改的话就是做个判断，下载前临时修改全局`aria2_jsonrpc`跟`aria2_secret`，然后下载触发后改回来。但是这个会影响一些东西。比如你正在准备抓取然后又操作了右键菜单的不同按钮。

> 不然这交互非常有问题。

我前面也说了，这东西是因为你提出我才开始加，我个人是没这个需求的，popup那边也没做切换，甚至popup的代码也要彻底改一遍，甚至keep-alive相关也要变。就挺难受的。

**Comment by jc3213** [comment]
把`aria2.js`以class形式重写了，用以适配多档案……

**Comment by jc3213** [comment]
更新到最新的12.1了，现在看起来修改点真的小……

**Comment by jc3213** [comment]
同步基础代码到3.13.0

**Comment by jc3213** [comment]
同步到3.13.4

**Comment by ivysrono** [comment]
3.13.7的两个版本区别是？

**Comment by jc3213** [comment]
参考 https://github.com/jc3213/download_with_aria2/discussions/31

主要是把需要用`Web Socket`连接的`notifications`相关的内容放到一个独立的`Shared Worker`里了，然后通过`worker.port`进行信息交流。让`Background`跟`Popup`只通过一个`WebSocket`连接就能同时实现交互。而且并且优化了部分逻辑（这个忘了放到普通版本以及`Multi Profile`里面了）。

刚开启discussion的时候有不少问题，现在已经优化得差不多了。我主要是看将来`Service Worker`可以访问`Shared Worker`因此才考虑这么操作的，目前还不准备并入主分支或者`Multi Profile`分支。

至于`Multi Profile`，有机会也会考虑好好优化一下逻辑

**Comment by ivysrono** [comment]
3.13.7不能下载北大法宝了，别的没多测试，退回3.13.6

**Comment by jc3213** [comment]
尽量用新issue吧，老issue翻起来太麻烦了

**Comment by ivysrono** [comment]
貌似3.13.8好了。
那我今后应该传哪个？

**Comment by jc3213** [comment]
3.13.8是因为我把代码啥的重新整理了一下，以后应该也很难再出问题了。

既然已经传了multi profile就按multi profile来吧。shared worker这个我感觉看情况再说。主要manifest v3直接用service worker。

service worker里面无法访问shared worker或者web worker。同时service worker会自动休眠无法keep alive，也就是任何setTimeout或者setInterval都会在休眠后自动失效，web socket连接也会自动断开。

然后谷歌也说要强制扩展迁移到manifest v3。但是有一说一，service worker的性质就不适合做background，所以我看看其他扩展怎么做的兼容再说自己这边。
