### ISSUE TITLE
Can no longer name download

### ISSUE THREAD

**Issue by gbcox** [jc3213/download_with_aria2#19]
Using with Firefox.  The previous versions allowed you to name the download using the Firefox dialog, but the new version does not do this... it just automatically starts the download.  Can you please fix?  Version 3.10.7 has this problem.  The 2.4.9 version works fine.  Seems a bit strange that you lose functionality if you use the latest version.

**Comment by jc3213** [comment]
You can go `about:addons` open the extension options, you will see `Safe Mode` if you are later than version `3.9.x`.

Click on `Safe Mode` Will show a prompt, check `OK` then you will see hidden options (For advanced user), switch API back to `downloads API` if you would like to.

This referers to https://github.com/jc3213/download_with_aria2/issues/7

**Comment by jc3213** [comment]
I will set default api back to `downloads API` in [3.12.0](https://github.com/jc3213/download_with_aria2/releases/tag/3.12.0)
