### ISSUE TITLE
忽略域名可能失效

### ISSUE THREAD

**Issue by ivysrono** [jc3213/download_with_aria2#27]
![图片](https://user-images.githubusercontent.com/2649544/156886464-2899e9ad-6b88-4413-8c93-e6ab47e7d415.png)
https://riot-optimizer.com/thank-you-for-downloading-riot/?sid=portable-app
还是会被接管

**Comment by jc3213** [comment]
你得用当前网站得`SLD.TLD`，`riot-optimizer.com`

**Comment by ivysrono** [comment]
原来如此
