### ISSUE TITLE
[Feature Request] 不显示下载通知

### ISSUE THREAD

**Issue by hosxy** [jc3213/download_with_aria2#28]
能否增加一个选项，不显示 如下图的下载通知
![图片](https://user-images.githubusercontent.com/17108640/159118869-bf5a6738-d0a5-4445-be50-d0e305846302.png)

**Comment by jc3213** [comment]
直接长按这个通知就可以选择是否弹出通知了来着？

**Comment by hosxy** [comment]
> 直接长按这个通知就可以选择是否弹出通知了来着？

好像不行，笔记本不是触摸屏，鼠标左键长按和单击效果是一样的，直接消失，没有弹出选项

**Comment by jc3213** [comment]
> > 直接长按这个通知就可以选择是否弹出通知了来着？
> 
> 好像不行，笔记本不是触摸屏，鼠标左键长按和单击效果是一样的，直接消失，没有弹出选项

Chromium那边倒是有个设置按钮，长按也能实现阻止通知。火狐我回头看看

**Comment by jc3213** [comment]
参考 https://www.reddit.com/r/firefox/comments/n73flz/comment/gxdjxa7/?utm_source=share&utm_medium=web2x&context=3

地址栏输入`about:debugging#/runtime/this-firefox`（即附加组件的Debug模式）
点击扩展的`Manifest URL` 我这边的样例为 `moz-extension://cdbf25cc-8933-429d-a66d-bd5f57e4806d/manifest.json`
按下快捷键`Ctrl+I`
选择`Permissions` > `Send notifications` > `Block`

**Comment by jc3213** [comment]
又找到个方法

- 打开`about:devtools-toolbox?id=firefox%40downloadWithAria2&type=extension`，选择`Console`
- 输入`browser.permissions.remove({permissions: ['notifications']})`

但是我实测火狐下面依然不正常。鬼知道怎么回事了。从源代码上我不准备做更多处理了。

**Comment by jc3213** [comment]
已修复
