### ISSUE TITLE
[Feature Request] 使用当前浏览器的 UserAgent

### ISSUE THREAD

**Issue by hosxy** [jc3213/download_with_aria2#29]
能否增加一个选项，直接使用当前浏览器的 UserAgent

**Comment by jc3213** [comment]
直接修改User Agent设置不就好了？

**Comment by hosxy** [comment]
> 直接修改User Agent设置不就好了？

那浏览器版本每次升级都要改一次

**Comment by jc3213** [comment]
保持旧的浏览器版本也不会有太大问题啊？其他下载工具也差不多的设置逻辑（IDM，FDM，迅雷）。
