### ISSUE TITLE
3.13.5 下载 xpi

### ISSUE THREAD

**Issue by ivysrono** [jc3213/download_with_aria2#30]
amo又抓取xpi了

**Comment by jc3213** [comment]
额，如果用`webRequest API`的话推荐自己把xpi添加到例外吧。这里的相关代码直接从background操作的话，感觉太武断了。

**Comment by ivysrono** [comment]
ok

**Comment by jc3213** [comment]
如果是在background进行处理，只要匹配到特定条件就会把xpi放到例外规则里面，或者直接进行例外操作，这样想反过来操作就做不到了。只有手动修改规则才合理。

**Comment by ivysrono** [comment]
只对amo的xpi操作比较合理，不过不是什么大事就这样吧
