### ISSUE TITLE
3.14.0 webRequest 模式无法排除 xpi

### ISSUE THREAD

**Issue by ivysrono** [jc3213/download_with_aria2#32]
已经将 xpi 写入忽略后缀，addons.mozilla.org 写入忽略域名，但依然接管了。

改成 downloads API 即可符合预期。

**Comment by jc3213** [comment]
默认情况下只匹配 `SLD.TLD` 这个格式，当SLD满足部分TLD的时候，比如`com`, `net`, `org`, `edu`, `gov`, `co`, `ne`, `or`, `me`的时候，则需要匹配 `SUB.SLD.TLD`

比如你说的这里就是`addons.moziila.org` => SUB `addons`, SLD `mozilla`, TLD `org`。SLD的`mozilla`没满足上面的条件，因此匹配`SLD.TLD`，即`mozilla.org`

**Comment by ivysrono** [comment]
这个逻辑太反直觉了。我的第一反应是 host.endsWith(...)
另外，为啥xpi排除也失效了呢？

**Comment by jc3213** [comment]
> 这个逻辑太反直觉了。我的第一反应，或者说我一直以为是类似于 host.endsWith(...)

因为储存是array，用遍历array然后匹配host.endsWith感觉比较慢？刚测试了下先匹配整个hostname，再匹配sld.tld都比直接用这个方案更好。
![test](https://user-images.githubusercontent.com/8744936/162971927-bc589f1e-a380-46f3-9fe0-329edecdd1ae.png)

> 另外，为啥xpi排除也失效了呢？
这个我明天测试下，理论上不至于啊？后面改的都跟这部分无关啊？有点迷……

**Comment by jc3213** [comment]
我测试`webRequest`API，完全能例外XPI的抓取啊？
![setting](https://user-images.githubusercontent.com/8744936/163076054-25812e1e-d6cd-4418-afd6-66fb0a6edeaa.png)
![action](https://user-images.githubusercontent.com/8744936/163076060-a7d8a13f-1597-4246-9329-b6c8865c7089.png)

**Comment by jc3213** [comment]
实在不行你试试最新的源代码？ [multi profile](https://github.com/jc3213/download_with_aria2/tree/multiprofile)

感觉可能跟 https://github.com/jc3213/download_with_aria2/commit/694fc5f0d69d6adb30b69d13a5c2c43e5c075348#diff-f8327d456eb627712c0d419126894ea390b29d00c00b7727ad53e6fffbc17aa0R51 这里的 51行有关

**Comment by ivysrono** [comment]
不设置任何域名排除规则，仅设置排除XPI后缀名：
main 889 符合预期排除
multi 889 继续捕获下载

**Comment by ivysrono** [comment]
那我下个版本开始切换回main。
还有个可能是升级导致的问题，我发现几次了，需要卸载重装才能符合预期，怀疑升级和测试过程中破坏了配置。

**Comment by jc3213** [comment]
main到multi并不是直接就能切换过去的……关于储存方面我也有想修改的东西。不过再说了……

**Comment by jc3213** [comment]
话说可以的话帮忙测试一下最新版。稍微优化了点逻辑。就是我最近可能没时间测试。

**Comment by ivysrono** [comment]
测试下来没有发现问题

**Comment by jc3213** [comment]
我前几天键盘坏了，用手机在QQ上打字然后复制粘贴到Github。代码是在网吧敲的。人傻了
