### ISSUE TITLE
Firefox 启用第一方隔离功能后无法抓取下载

### ISSUE THREAD

**Issue by lianelc0299** [jc3213/download_with_aria2#35]
macOS Fx ESR 91.11.0
启用 Cookie 第一方隔离后，无法抓取下载，也无法使用右键菜单调取下载，但是手动创建下载可以进行。
关闭第一方隔离后一切正常。

**Comment by jc3213** [comment]
第一方隔离？不知道能否提供更多的信息？

**Comment by jc3213** [comment]
稍微查了下资料，在`browser.cookies.getAll()`的时候添加了参数`firstPartyDomain: null`，理论上已经解决了这个问题（至少我自己测试能正常获取Cookie）

**Comment by lianelc0299** [comment]
> 稍微查了下资料，在`browser.cookies.getAll()`的时候添加了参数`firstPartyDomain: null`，理论上已经解决了这个问题（至少我自己测试能正常获取Cookie）

:smile: 确实已解决，感谢！
