### ISSUE TITLE
it cannot work in some websites

### ISSUE THREAD

**Issue by yushu280** [jc3213/download_with_aria2#36]
In some websites , it can get the link and send to aria2, but  it failed to download.  For example , the website "https://kinhdown.com/?Type=APPS".

**Comment by jc3213** [comment]
I‘ve tested on that site and found that, downloads from `https://api.kinh.cc/KinhDown/WinDowsData/DownLoad.php` were broken, and others works fine.

I’m using Chromium based browser though.

**Comment by jc3213** [comment]
It seems that you can download only if you do not pass any `Request Headers` for this download.

For example, [KinhDown BaiDu Beta for WinDows](https://img.kookapp.cn/attachments/2022-07/26/62dee257c92cd)

It can be download if you add the download through `New` button, but can not be downloaded if you use `contextmenu` or `download capturing`

It is not possible for me to fix from my side if I have to rewritten all the whole mechanism.

**Comment by yushu280** [comment]
Thanks.

**Comment by jc3213** [comment]
Since in 4.0.0, there is an option `Prompt Download Window` aka `确认下载信息` in Chinese. You can check this, then try to delete `Referer` from the `New Download Window`. Or, you can uncheck `Forward Request Header` aka `转发请求头` in Chinese to work around. Sorry this will not be `rule based`

**Comment by yushu280** [comment]
> 

Thanks，it can work when I donot select the Request Header

**Comment by jc3213** [comment]
I'm tring get `requestHeaders` from `webRequest.onBeforeSendHeaders`, I've accessed `https://kinhdown.kinh.cc/?Type=APPS` and tried to download the apps below. But however, either I get headers from `webRequest` or `downloads` and `cookies`，I don't met any download issue there. Do you have any other sites for me to test?
