### ISSUE TITLE
【功能请求】为 Firefox 增加激活工具栏按钮的快捷键

### ISSUE THREAD

**Issue by wordpure** [jc3213/download_with_aria2#40]
Firefox 不像 Chrome 和 Edge 那样自带这个扩展快捷键，查看和管理下载内容的时候必须手动点击工具栏上的按钮，次数多了就有点烦😂

希望作者能给 Firefox 加上这个扩展快捷键。

**Comment by jc3213** [comment]
我真不知道怎么做，不过看火狐有很多快捷键扩展，希望你能试试那边？我查了下DMO没发现相关文献

**Comment by jc3213** [comment]
> [commands - Mozilla | MDN](https://developer.mozilla.org/en-US/docs/Mozilla/Add-ons/WebExtensions/manifest.json/commands)
> 
> 这里有介绍怎么给 Firefox 扩展添加快捷键。
> 
> 我看了下还挺简单的，就提了 PR 混个协作者😊

我搜索的是shortcut……好吧，不管怎样感谢了，就是希望你把你的PR做一下pretty print。如果人人得PR都改变代码得排布，那最后就会乱成一锅粥

**Comment by wordpure** [comment]
> 就是希望你把你的PR做一下pretty print。如果人人得PR都改变代码得排布，那最后就会乱成一锅粥

抱歉，之前没怎么提过 PR，忽略了这个地方。

**Comment by wordpure** [comment]
另外我看了一下，manifest 的 `default_locale`  字段这里多了个空格，我提交的时候一起改掉还是？

![图片](https://user-images.githubusercontent.com/68013962/189256589-70b7baee-7086-42b3-8b83-004d44b1192a.png)

**Comment by jc3213** [comment]
可以的话一起改掉吧，我有时候检查不过来……

**Comment by wordpure** [comment]
提交了。

还意外地发现 developer 这里只有 7 个空格，顺便一起改了😂

![图片](https://user-images.githubusercontent.com/68013962/189299092-f18a86b9-49b2-4486-af3a-7fd1822b394e.png)

**Comment by jc3213** [comment]
麻烦了，我这边有时候用平板，有时候用电脑，反正很容易出问题……

**Comment by wordpure** [comment]
@jc3213 

`Ctrl + Shift + A ` 是 Firefox 打开附加组件页面的默认快捷键，不适合做扩展快捷键。

![图片](https://user-images.githubusercontent.com/68013962/189381733-3e65c43b-dc41-4925-855b-980cdd852109.png)

**Comment by wordpure** [comment]
`Alt + Shirft + A` 或 `Alt + A` 可以，不过其他含 `Alt` 的快捷键就要慎重使用了。

因为 `Alt` 在 Firefox 中默认用于激活菜单栏，而且优先级还比扩展快捷键高😂如果设置了与菜单项重复的字母，它基本无法工作，必须要手动到 `about:config` 中修改才行。

![图片](https://user-images.githubusercontent.com/68013962/189385649-6535ed87-ee5b-45d0-9ddc-cde31672789f.png)

**Comment by jc3213** [comment]
每个浏览器设置不同，`Proxy SwitchyOmega`是Ctrl+Shift+O，但是在Vivaldi里用不了，最开始我是准备用Ctrl+Shift+Q的，然后也是发现用不了。更别提国内各种Chromium套壳，火狐也还有变种。

反正目前还没准备推送正式版。先看看Ctrl+Shift能配什么，如果用1或者0的话，Chromium这边可以设置成global属性，我个人还是很推荐的。具体只能多来几个人慢慢测，我自己的精力有限……

**Comment by wordpure** [comment]
[浏览器快捷键.xlsx](https://github.com/jc3213/download_with_aria2/files/9539567/default.xlsx)

我把 [Firefox](https://support.mozilla.org/zh-CN/kb/%E9%94%AE%E7%9B%98%E5%BF%AB%E6%8D%B7%E9%94%AE)、[Chrome](https://support.google.com/chrome/answer/157179?hl=zh-Han)、[Edge](https://support.microsoft.com/zh-cn/microsoft-edge/microsoft-edge-%E4%B8%AD%E7%9A%84%E9%94%AE%E7%9B%98%E5%BF%AB%E6%8D%B7%E6%96%B9%E5%BC%8F-50d3edab-30d9-c7e4-21ce-37fe2713cfad) 和 [Cent](https://www.centbrowser.cn/features.html) 官方文档里列出来的快捷键加到 Excel 里了，以后可以先按工作簿查找看看。

Vivaldi 没找到官方的快捷键文档，就用了 [第三方](https://www.hongkiat.com/blog/vivaldi-keyboard-shortcuts/) 的。

![图片](https://user-images.githubusercontent.com/68013962/189468735-1c5c2ccc-1093-4d29-822f-eafd1cd3b795.png)

**Comment by wordpure** [comment]
> 先看看Ctrl+Shift能配什么，如果用1或者0的话，Chromium这边可以设置成global属性，我个人还是很推荐的。

Chromium 自带的激活工具栏按钮快捷键不能设置为全局的吧？要有独立窗口那种才行。

**Comment by wordpure** [comment]
> 然后Alt+Shift这个快捷键是Windows系统的输入法→语言切换用的快捷键，对我这个用三种语言打字的表示很怕干扰，所以我不推荐Alt+Shift

涨知识了👍

**Comment by wordpure** [comment]
其实我觉得可以不用给扩展设置默认快捷键的，有这方面需求的自己会去设置，没有这方面需求的根本不会注意到它。

而且好用的快捷键就那么多，很容易就和其他软件或扩展程序设置的冲突了。

**Comment by jc3213** [comment]
> 其实我觉得可以不用给扩展设置默认快捷键的，有这方面需求的自己会去设置，没有这方面需求的根本不会注意到它。
> 
> 而且好用的快捷键就那么多，很容易就和其他软件或扩展程序设置的冲突了。

我也是这个思路，参考Proxy SwitchyOmega的快捷键其实也有问题，所以想暂时留个底罢了。至少在Chromium这边拥有了默认快捷键，Firefox那边有了接口——貌似没`commands`就没接口
