### ISSUE TITLE
Upon .torrent file download finishing, aria2 starts downloading the actual files

### ISSUE THREAD

**Issue by escape0707** [jc3213/download_with_aria2#42]
I don't remember this behavior existed earlier. What changed or, what should I change to prevent this?

**Comment by jc3213** [comment]
I wonder if your task number is over `max-concurrent-downloads` (which default is 5). So if a task is finished, other tasks in `waiting` queue will be sent to `active` queue thus starts aother download

**Comment by escape0707** [comment]
Thanks for your speedy reply.

I'm not running too much downloading tasks simultaneously.

This is the configuration my aria2 RPC server is using:

```ini
auto-file-renaming=false
continue=true
enable-rpc=true
file-allocation=falloc
log-level=warn
max-concurrent-downloads=3
max-connection-per-server=4
min-split-size=1M
rpc-secret=zzhhbyt2
split=99999
```

And I only downloaded one `.torrent` file. When the downloading of the file finished, Aria2 started the BT download of the torrent, which is not what I wanted. I mainly use qBittorrent for that.

**Comment by jc3213** [comment]
> And I only downloaded one `.torrent` file. When the downloading of the file finished, Aria2 started the BT download of the torrent, which is not what I wanted. I mainly use qBittorrent for that.

If you use aria2 to download for example `https://test.com/test.torrent`. When the `HTTP` downloads is complete, aria2 will start a `Bit Torrent` download based on `text.torrent`. It is aria2's default behavior

**Comment by escape0707** [comment]
Sorry, but can you elaborate more about what's `text.torrent`? Is that something about MIME?

**Comment by jc3213** [comment]
Sorry, that's a typo. I means aria2 will download `.torrent` file from http server, then read the `.torrent` file and start a bit-torrent download automatically. Here's option from aria2's document to disable it

--dry-run [true|false][¶](https://aria2.github.io/manual/en/html/aria2c.html#cmdoption-dry-run)
If true is given, aria2 just checks whether the remote file is available and doesn't download data. This option has effect on HTTP/FTP download. BitTorrent downloads are canceled if true is specified. Default: false

**Comment by escape0707** [comment]
Doesn't that option completely skip the downloading of normal HTTP tasks?

**Comment by jc3213** [comment]
Oops, my fault, it should be

`--follow-torrent=true|false|mem`[Reference](https://aria2.github.io/manual/en/html/aria2c.html#cmdoption-follow-torrent)
If true or mem is specified, when a file whose suffix is .torrent or content type is application/x-bittorrent is downloaded, aria2 parses it as a torrent file and downloads files mentioned in it. If mem is specified, a torrent file is not written to the disk, but is just kept in memory. If false is specified, the .torrent file is downloaded to the disk, but is not parsed as a torrent and its contents are not downloaded. Default: true

**Comment by escape0707** [comment]
Oh, thanks! I didn't realize that the default to that option is `true`...

Guess I should update my configs.

**Comment by jc3213** [comment]
I use aria2 as my default download manager so I haven't changed many options. I'm happy if your problem is solved 👍
