### ISSUE TITLE
【功能请求】适配深色模式

### ISSUE THREAD

**Issue by wordpure** [jc3213/download_with_aria2#44]
如题，希望弹出窗口和选项界面可以适配深色模式。

**Comment by wordpure** [comment]
顺带一提，「弹出窗口 - 新下载 - 用户代理」这里的文本没有正常显示。

![图片](https://user-images.githubusercontent.com/68013962/198867947-6b215845-d6af-469d-b52e-bd1468bfa740.png)


看了下，是用户代理在 [popup/index.html](https://github.com/jc3213/download_with_aria2/blob/main/chromium/popup/index.html#L48) 和 [messages.json](https://github.com/jc3213/download_with_aria2/blob/main/chromium/_locales/zh/messages.json#L116) 的 i18n 名称没有对上。

![图片](https://user-images.githubusercontent.com/68013962/198868321-f68ff048-718e-408f-b11d-2635dc7fcedf.png)

![图片](https://user-images.githubusercontent.com/68013962/198868314-d95d567b-e9c4-4c1f-89fb-60b5a66fe8df.png)

**Comment by jc3213** [comment]
额，我记得这里是批量查找替换做的，oops。

新版本才能修复，但是没时间……

新版本预计把新下载窗口重新独立化，然后像火狐的某个扩展那样……

**Comment by wordpure** [comment]
> 新版本才能修复，但是没时间……

不急，大佬有空再改吧。

> 新版本预计把新下载窗口重新独立化，然后像火狐的某个扩展那样……

指的是 [Aria2-AriaNG下载组件](https://addons.mozilla.org/zh-CN/firefox/addon/aria2-ariang/)  吗？

期待😁

**Comment by jc3213** [comment]
准确的说是这个 https://github.com/RossWang/Aria2-Integration

**Comment by wordpure** [comment]
> 准确的说是这个 [RossWang/Aria2-Integration](https://github.com/RossWang/Aria2-Integration)

老前辈了

**Comment by jc3213** [comment]
另外关于深色模式，回头我研究下，毕竟只是个纯HTML网页。

**Comment by jc3213** [comment]
我这边用 `chrome://flags/#enable-force-dark` 测试，我这边的内容能自动成Dark Mode，不知道火狐有没有类似的开关？

**Comment by wordpure** [comment]
貌似没有。

设置里有一个覆盖颜色的选项，但效果很不理想。

![图片](https://user-images.githubusercontent.com/68013962/199689370-c04ec829-2e0e-4209-b27d-5a0620711937.png)

![图片](https://user-images.githubusercontent.com/68013962/199690465-6fff52ae-b1a9-4c04-ba50-ad4948e74d38.png)

**Comment by jc3213** [comment]
Chromium的话打开后是下面的效果，火狐自己的Dark Mode怎样？

![options](https://user-images.githubusercontent.com/8744936/199731856-a6f1c9d8-d7ca-4686-a76b-21c5f813512c.png)
![manager](https://user-images.githubusercontent.com/8744936/199731870-7ac55602-9a00-4ad0-8af1-7b161515c58b.png)
![manager-task](https://user-images.githubusercontent.com/8744936/199731885-3eed8411-9854-4a85-a161-77a34ebbecbe.png)
![newdownload](https://user-images.githubusercontent.com/8744936/199731893-886c16e1-e397-4f2c-86df-c188fb122f95.png)

**Comment by jc3213** [comment]
https://developer.mozilla.org/en-US/docs/Web/CSS/@media/prefers-color-scheme#:~:text=The%20prefers-color-scheme%20CSS%20media%20feature%20is%20used%20to,theme,%20or%20has%20not%20expressed%20an%20active%20preference.

参考了这个，但是没卵用，估计你的下载扩展来实现类似功能了

**Comment by wordpure** [comment]
背景全黑，字体全白😂

![图片](https://user-images.githubusercontent.com/68013962/199736382-9f8e0840-655c-469a-ac88-bb9c530fe854.png)

![图片](https://user-images.githubusercontent.com/68013962/199736404-d5c22d62-9c2b-4155-bc56-ce057127c8c4.png)

![图片](https://user-images.githubusercontent.com/68013962/199737121-e8127066-2e7f-49aa-8ba1-a7def1af9961.png)

**Comment by jc3213** [comment]
我这边用 `@media (prefers-color-scheme: dark) { css code }` 根本没效果，估计只能用js流方案，但是感觉有点裂开。感觉你用扩展会好点。

**Comment by wordpure** [comment]
> 感觉你用扩展会好点。

扩展程序的页面，其他扩展影响不了的，只能靠扩展自己实现或浏览器级别的设置。

> 我这边用 `@media (prefers-color-scheme: dark) { css code }` 根本没效果，估计只能用js流方案，但是感觉有点裂开

这么奇怪？我试一下。

**Comment by jc3213** [comment]
JS的方案如下，或者在css里面做一个class，然后识别出来以后直接给body添加这个class。但是我这边开了dark mode测试都是false，很怪。

```javascript
if (window.matchMedia('(prefers-color-scheme: dark)').matches) {
    var dark = document.createElement('style');
    dark.innerText = `{
          // you preferred dark css code
    }`;
}
```

![false](https://user-images.githubusercontent.com/8744936/199743007-5965072e-7fea-4cc6-bec2-2b69020470d5.png)

**Comment by jc3213** [comment]
可能是Vivaldi有bug吧，毕竟这浏览器为了整所谓的花哨theme已经把`chrome.browserAction.setBadgeBackgroundColor`给弄炸了。至于这里我回头换火狐再弄吧。

目前基础功能还需要调优

**Comment by wordpure** [comment]
> 可能是Vivaldi有bug吧，毕竟这浏览器为了整所谓的花哨theme已经把`chrome.browserAction.setBadgeBackgroundColor`给弄炸了。至于这里我回头换火狐再弄吧。

你看我这里的配色还行不？

可以的话我直接提个 PR？

**Comment by jc3213** [comment]
这个到时候我根据Chromium的版本来弄。

**Comment by jc3213** [comment]
细节还需要微调，但是感觉总是不对。有个啥参考就好了

**Comment by jc3213** [comment]
帮忙测试下最新的main分支，如果没问题dark mode我就不管去做其他优化了

**Comment by wordpure** [comment]
效果还不错，就是彩色按钮的文本对比度差了点，button、select 和 input 不好区分。

![图片](https://user-images.githubusercontent.com/68013962/199961726-902b702a-6d86-4dac-b7ca-b0d1cc8a9bfd.png)

![图片](https://user-images.githubusercontent.com/68013962/199961626-73fb9fe4-c6bb-45ab-b9ca-3dce750e407e.png)

**Comment by jc3213** [comment]
我只是单纯觉得跟背景区分开就行了。分别参考了chromium的强制dark mode，github的dark mode跟mdn打开`prefers-color-scheme: dark`以后的效果。不知道为啥你那边跟我这边差距感觉有点明显？
![1](https://user-images.githubusercontent.com/8744936/199963794-6772d138-55df-495d-9720-913ea6863c58.png)
![2](https://user-images.githubusercontent.com/8744936/199963808-63418f58-4699-473e-92b1-71761c201e3c.png)
![3](https://user-images.githubusercontent.com/8744936/199963811-84dde822-79c2-4765-a24b-6cd4401f6862.png)
![4](https://user-images.githubusercontent.com/8744936/199963814-70abde4d-755b-4edf-985e-36e2411e18b4.png)
![5](https://user-images.githubusercontent.com/8744936/199963818-e1aedd20-a6f9-48e6-835b-943e63811e64.png)

**Comment by wordpure** [comment]
可点击和不可点击的按钮只有边框颜色有细微差别，不好区别。

![图片](https://user-images.githubusercontent.com/68013962/199966864-9adcf81a-0ea6-42a4-bbe2-8ec14d5ee6b6.png)

**Comment by wordpure** [comment]
> 不知道为啥你那边跟我这边差距感觉有点明显？

你看我上两张截图就行，昨天发的截图是我自己改的配色，和现在不是同样的 CSS。

![图片](https://user-images.githubusercontent.com/68013962/199967408-2d7c4bd4-84b4-45ae-b30a-dda466984e4a.png)

**Comment by jc3213** [comment]
现在呢？

**Comment by wordpure** [comment]
现在按钮好辨别多了🌹

![图片](https://user-images.githubusercontent.com/68013962/200004383-0aa628f0-5f35-47c9-8e29-bbda963b1019.png)
