### ISSUE TITLE
is there any information on how to enable aria2 on the wiki or README.md?

### ISSUE THREAD

**Issue by candrapersada** [jc3213/download_with_aria2#46]

**Comment by jc3213** [comment]
You mean how to run `aria2c.exe` as a jsonrpc server? Maybe https://github.com/jc3213/batchscript will help you.

**Comment by candrapersada** [comment]
what I mean is for other OS than Windows like Linux

**Comment by jc3213** [comment]
Oops, i don't quite familiar with Linux. But you can run
```
aria2c --enable-rpc=true --rpc-allow-origin-all=true --rpc-listen-all=true --rpc-secret=${YOUR TOKEN}
```
Official document here
https://aria2.github.io/manual/en/html/aria2c.html

**Comment by jc3213** [comment]
I've also complete most part of documentation in [Wiki](https://github.com/jc3213/download_with_aria2/wiki)
