### ISSUE TITLE
program works nicely and quickly + download prompt improvement suggestion

### ISSUE THREAD

**Issue by cyberhardt** [jc3213/download_with_aria2#60]
hi, your extension was the only one that worked properly with my ariang native client. the 3 other extensions I've tested either didn't work, or had their own aria ng client which I don't need. great program. my only suggestion is that you enhance your download prompt so that it is possible to open an explorer window to select the place you want to download the file. as of now, you have to manually type the path on the download prompt, which works but isn't ideal.

**Comment by jc3213** [comment]
I was once tried to do that, but I don't know how to coding. I've also tried
```
<input  type="file" webkitdirectory>
```
But it prompts "upload all files in seleted directory? yes/cancel"

If you can provide any extension or website that can select directory without any prompt, please let me know

**Comment by cyberhardt** [comment]
> hi, your extension was the only one that worked properly with my ariang native client. the 3 other extensions I've tested either didn't work, or had their own aria ng client which I don't need. great program. my only suggestion is that you enhance your download prompt so that it is possible to open an explorer window to select the place you want to download the file. as of now, you have to manually type the path on the download prompt, which works but isn't ideal.

by the way, it is possible to use the extension stand-alone, without the use of AriaNG or any other client, which is what makes this extension so powerful. as long as you have aria2c.exe running, and a properly configured .conf,  this extension can do all the work, with a fraction of the size and memory consumption of a program like AriaNG (it uses ~150MB of RAM on idle).

**Comment by cyberhardt** [comment]
> I was once tried to do that, but I don't know how to coding. I've also tried
> 
> ```
> <input  type="file" webkitdirectory>
> ```
> 
> But it prompts "Upload all files in seleted directory? Upload/Cancel"
> 
> If you can provide any extension that can select directory without any prompt, please let me know

What you can do that makes this easier than having to type it is: when you download a file, before the extension comes with its own prompt, there is an explorer prompt, in which you can select the download path as if the browser was going to downloading. When that happens, simply copy the path as text, and then paste it on the extension prompt. Provided you don't forget this method, it will be very quick and effortless.

**Comment by jc3213** [comment]
> by the way, it is possible to use the extension stand-alone, without the use of AriaNG or any other client, which is what makes this extension so powerful. as long as you have aria2c.exe running, and a properly configured .conf, this extension can do all the work, with a fraction of the size and memory consumption of a program like AriaNG (it uses ~150MB of RAM on idle).

This extension is rewritten from https://github.com/robbielj/chrome-aria2-integration 

There are no smooth animations for UI, also bad coded for `Manifest V3`, it is only a simple and easy to use one so it won't consume much computer resources

> You can do this instead of typing it: when you download a file, before the extension comes with its own prompt, there is an explorer prompt, in which you can select the download path as if the browser was going to download it. When that happens, simply copy the path as text with a right-click, and then paste it on the extension prompt that follows. Provided you don't forget to copy the path when the explorer window appears, it is a quick, effortless method.

I mean that I've once tried to make a selector for `Download Folder`, but it doesn't work as expected, I've see many other userscripts or extensions that also uses `<input type="text">` for folder entries

**Comment by cyberhardt** [comment]
> This extension is rewritten from https://github.com/robbielj/chrome-aria2-integration
> 
> There are no smooth animations for UI, also bad coded for `Manifest V3`, it is only a simple and easy to use one so it won't consume many computer resources

And this is what makes it so great. Smooth animations aren't necessary. Its small size and performant nature are strengths, not weaknesses. It isn't a chrome extension, so support for Manifest V3 isn't needed - firefox is much better anyway.

> I mean that I've once tried to make a selector for Download Folder, but it doesn't work as expected, I've see many other userscripts or extensions that also uses <input type="text"> for folder entries

I know, I'm just saying that there is a way to quickly input the file path so that making an explorer window isn't a priority for now.

**Comment by jc3213** [comment]
> firefox is much better anyway.

If you're using Firefox, you can try `Follow Browser Behavior` in **Options**, which needs to turn off `Capture Web Request` to work.

But `Capture Browser Downloads` without `Capture Web Request` is somehow a crack in Firefox because of its behavior

**Comment by cyberhardt** [comment]
> > firefox is much better anyway.
> 
> If you're using Firefox, you can try `Follow Browser Behavior` in **Options**, which needs to turn off `Capture Web Request` to work.
> 
> But `Capture Browser Downloads` without `Capture Web Request` is somehow a crack in Firefox because of its behavior

I couldnt find any of the options you mentioned

**Comment by jc3213** [comment]
Oops, that's broken by [4.2.4.1965](https://github.com/jc3213/download_with_aria2/releases/tag/4.2.4.1965), and has been fixed in https://github.com/jc3213/download_with_aria2/commit/51856de05d1c0f36f06413ccfd9031a83dc62c89

**Comment by cyberhardt** [comment]
> Oops, that's broken by [4.2.4.1965](https://github.com/jc3213/download_with_aria2/releases/tag/4.2.4.1965), and has been fixed in [51856de](https://github.com/jc3213/download_with_aria2/commit/51856de05d1c0f36f06413ccfd9031a83dc62c89)

alright waiting for update on the firefox store

**Comment by cyberhardt** [comment]
oh ok it was already updated, I'll test it

**Comment by cyberhardt** [comment]
it's working

Follow Browser Behavior allows you to set the download directory as if you were downloading with the browser, great, thank you
