### ISSUE TITLE
Feature Request

### ISSUE THREAD

**Issue by hl2guide** [jc3213/download_with_aria2#63]
Please consider adding a _Completed_ tab/filtering after _Active Waiting Stopped_ at the top.

**Comment by jc3213** [comment]
As have metioned in many issues, this extension is rewritten from https://github.com/robbielj/chrome-aria2-integration

> Please consider adding a Completed tab/filtering after Active Waiting Stopped at the top.
There's no enough space for another filter button and task counter.

If you'd like a more powerful and modern Task Manager, try  [Aria2 WebUI](https://ziahamza.github.io/webui-aria2/) or [AriaNG](https://aria2ng.github.io/)

> Please change button icons to match their functions
> Please add tooltips for all buttons.
I have no icon resources so it's not possible for me to use emoji for buttons.

If you have issue with Task Manager, please read https://github.com/jc3213/download_with_aria2/wiki/TaskManager

Please don't spamming

**Comment by jc3213** [comment]
Fixed in [4.4.0.2108](https://github.com/jc3213/download_with_aria2/releases/tag/4.4.0.2108)
