### ISSUE TITLE
Sort by date added descending

### ISSUE THREAD

**Issue by char101** [jc3213/download_with_aria2#65]
Hi,

When a new downloaded is added, it is added on top in the active group status, then when completed it is moved to the bottom. This makes evaluating completed downloads less smooth because we have to scroll up and down.

It would be better if the downloads are sorted by the time added in descending order so there is less jumping around.

**Comment by jc3213** [comment]
First of all. **Don't Spamming**

I‘m afraid that will not be possible. I've splitted all download sessions into queues based on their running status. this is how Aria2 WebUI works. It's meaning less for a light-weight webui either.

If you will need a modern web ui, read [Wiki:Alternative Manager](https://github.com/jc3213/download_with_aria2/wiki#alternative-manager)
