### ISSUE TITLE
Webrequest capture notification

### ISSUE THREAD

**Issue by char101** [jc3213/download_with_aria2#66]
Hi,

When using the webrequest capture in firefox, there is no indication of whether the download has been successfully added. If would be good if the addon can provide a notification or other kind of indication that the downloaded have been successfully added to the queue.

**Comment by jc3213** [comment]
First of all. Don't Spamming**

You can check `Notifications` -> `When Download Start`， It will show notification when extension captured and sent download to aria2c

**Comment by char101** [comment]
Thanks, that actually works. The term start is ambiguous though, because the download has not actually been started (I don't like paralel downloading so I run my aria2c with `-j 1`, with more than one download, one the first item is started). A better term is probably _queued_ or _added_.

**Comment by jc3213** [comment]
Use `--rpc-listen-port=<PORT>` and let one of aria2c.exe listen to another port.
