### ISSUE TITLE
Less colorful progress bars

### ISSUE THREAD

**Issue by char101** [jc3213/download_with_aria2#67]
Hi,

I think it would be better if the progress bar follows the more common pattern

1. A completed download has a 100% green progres bar
2. A pending download has a transparent progress bar
3. An active download has a green section showing the progress of downloaded part

This will only use one color and make the interface simpler and cleaner.

**Comment by jc3213** [comment]
First of all. **Don't Spamming**

Use only one color can't show users whether the task is waiting in queue, or stopped by error, it will not be an option. 

But if you have any other suggestion on progress bar color, please let me know.

**Comment by char101** [comment]
Failed downloads are usually colored red, paused downloads are yellow, but I never see a pending downloads colored blue, which is not intuitive to me.

Also creating multiple issues by topic is not spamming.

**Comment by jc3213** [comment]
If your issue is needs more description or you want add pics to your issue, it is OK that you open multi issues.

If you send very short feature request more than 2 times, it is spamming.

Back to the issue, your suggestion is `Green` for **active** and **complete**, `Yellow` for **waiting** and **paused**, `Red` for **removed** and **error**.

Then how about the background color of the progress bar? I want it more clear that if the session is `Removed by User` or `Error Occured`

**Comment by char101** [comment]
> If your issue needs more description or you want to add pics to your issue, it is OK that you open multi issues.

I think you get it reversed, more description or picture should be added in the same issue, not another issue. And I never heard that making multiple issues in the short time is considered spamming, but if that is your preference, then sure.

> Back to the issue, your suggestion is Green for active and complete, Yellow for waiting and paused, Red for removed and error.

How about adding a red border to the progress bar for that?

From my experience this is how a progress bar usually look like

![223213](https://github.com/jc3213/download_with_aria2/assets/71255/c63ec6d4-3e30-48ea-abea-8b6f817e41a6)

An incomplete progress bar is usually a neutral color (white, black, or gray). Having it colored blue meses with the mind because the color blue usually means information or primary.

**Comment by jc3213** [comment]
The `Status Icon` in front of `Task Name` is a good idea. I have added `Queue` button and related function which uses the similar solution, but I haven't thought that I can do the the for the task status. Your suggestion was a great help.

**Comment by jc3213** [comment]
The change has been done in [ac23d0a](https://github.com/jc3213/download_with_aria2/commit/ac23d0ad37d0302990af84d9bbd03259b3ca8c3c) The whole UI looks very aweful and ugly. Maybe I'll try to use `Font Awesome` for icons.

**Comment by jc3213** [comment]
There will be a circle that indicates task running status in front of the task name, and progress bar will have no other coloring now.
