### ISSUE TITLE
Settings aren't preserved on Firefox

### ISSUE THREAD

**Issue by glu8716** [jc3213/download_with_aria2#68]
I'm using version 4.3.1.1994 on Firefox. Even if change settings, those aren't preserved when I close the settings page

**Comment by jc3213** [comment]
You should press `Save` button in the mainmenu on the top to save your changes.

**Comment by glu8716** [comment]
That's what I do. It works if, for example, I refresh the page. But as soon as I close the tab the settings go back to the default ones

**Comment by glu8716** [comment]
I've made a quick video to show my problem. Do you have any idea on what could possibly be causing this?

https://github.com/jc3213/download_with_aria2/assets/33501455/c6e313c5-ebd9-4d3c-a71a-652078877bd2

**Comment by jc3213** [comment]
It seems you've got some `Fatal Error` when initializing `Options`.

Have you updated from a very old version? The background storage have been changed about 3 or 4 times. The compatibility code have been removed every major update (for example, 4.2 => 4.3 is a major update)

You can try remove the extension then install a new one from AMO.

**Comment by glu8716** [comment]
I had a old version installed, but I uninstalled it before installing the new one. I've tried to uninstall and reinstall it again with no luck.

I've also tried in a Firefox clean profile and it seems to work fine there. There must be something wrong with this profile I'm using. I'm using the [arkenfox user.js](https://github.com/arkenfox/user.js), could it be related to some Firefox setting?

**Comment by jc3213** [comment]
You can open the console **F12** and see if there are error messages. And then you can type `aria2Store` to see if the storage works for you

**Comment by glu8716** [comment]
I get a `TypeError: url is undefined` error

**Comment by jc3213** [comment]
Tell me the result of `aria2Store` and `aria2RPC` like
![aria2Store](https://github.com/jc3213/download_with_aria2/assets/8744936/c408d6cf-c8ea-4731-b409-5e7ddf2e9dc9)

![aria2RPC](https://github.com/jc3213/download_with_aria2/assets/8744936/52621dd3-6b47-4a2d-ac79-03826629ae0a)

**Comment by glu8716** [comment]
I can't see any output in the console as I get only that error
![2023-06-10_11-58](https://github.com/jc3213/download_with_aria2/assets/33501455/4e7b8ad6-e95f-472c-9b8d-c464a071f9e5)

**Comment by jc3213** [comment]
Type `aria2Store` after `>>` and press **Enter** key, then `aria2RPC` and press **Enter** key

**Comment by glu8716** [comment]
![image](https://github.com/jc3213/download_with_aria2/assets/33501455/e4800709-b32b-400a-b9c9-b422628895df)
Here's the result

**Comment by jc3213** [comment]
It seems the storage haven't been initialized for you. I don't know what caused this. You'll need to install `Firefox Developer Edition` then debug the extension

You can try copy the code below, then paste them into the console, press **Enter**. Wait about 1~2 seconds to see if there's any error. If not, try open the `Options` again
```javascript
browser.storage.local.set({
    'jsonrpc_uri': 'http://localhost:6800/jsonrpc',
    'jsonrpc_token': '',
    'manager_newtab': false,
    'manager_interval': 10000,
    'folder_enabled': false,
    'folder_defined': '',
    'download_prompt': false,
    'download_headers': true,
    'notify_start': false,
    'notify_complete': true,
    'user_agent': 'Transmission/4.0.0',
    'proxy_server': '',
    'proxy_enabled': false,
    'proxy_always': false,
    'proxy_include': [],
    'capture_enabled': false,
    'capture_always': false,
    'capture_filesize': 0,
    'capture_resolve': [],
    'capture_include': [],
    'capture_reject': [],
    'capture_exclude': [],
    'folder_firefox': false,
    'capture_webrequest': false
})
```

**Comment by glu8716** [comment]
That worked, thanks! I can now save settings

**Comment by glu8716** [comment]
I'm still having some problems, not sure if related to this.
1) Downloads aren't captured automatically even if the setting is on, I have to manually right click > download  with Aria2 on a link;
2) Download percentage isn't updated in real time. It is only refreshed every 4/5 seconds.
