### ISSUE TITLE
it keeps trying to start torrents

### ISSUE THREAD

**Issue by cyberhardt** [jc3213/download_with_aria2#69]
the program keeps trying to start a torrent when I download a .torrent file. is there a way to stop this behaviour?

**Comment by jc3213** [comment]
See #42

**Comment by cyberhardt** [comment]
> See [#42 (comment)](https://github.com/jc3213/download_with_aria2/issues/42#issuecomment-1242602051)
> 
> You can change aria2 option `Auto Process Torrent` in **Options** either

thanks, I hadn't clicked on that button before because it says "Set JSON-RPC internet address", I wasn't aware it had more options

**Comment by cyberhardt** [comment]
@jc3213 the extension keeps returning the auto process torrent option to "true" even though I'm pressing "save" and doing everything correctly. seems to be related to https://github.com/jc3213/download_with_aria2/issues/68 but only certain options such as "auto process torrent" and "listening port" under json-rpc settings are having this problem.

**Comment by jc3213** [comment]
If you don't add `follow-torrent=false` to aria2c startup options, all options for aria2c will be reset to default when you restart aria2c jsonrpc

**Comment by cyberhardt** [comment]
even with the follow-torrent=false on aria2c.conf, it still defaults back to true on json-rpc options. that said, it doesn't seem to be processing them anymore.

**Comment by jc3213** [comment]
Thanks for reporting. I've just found the problem
https://github.com/jc3213/download_with_aria2/blob/028f675f4f15c741acdfb1acb2ff694257a04897/chromium/pages/options/options.js#L7
It should be `#aria2 input, #aria2 select` or `#aria2 :input`, that's my fault. BTW, your options in aria2c.conf will work with no problem
