### ISSUE TITLE
Use webRequest API for Firefox to avoid disk I/O

### ISSUE THREAD

**Issue by jc3213** [jc3213/download_with_aria2#7]
Since the development has reached its edge. I am focused on improving performance.

On Firefox, the `downloads.onCreated` event is triggered later than download is created. File may be written to the local disk once, then removed because the download is cancelled by this extention.

I want to rewrite capture code based on [Aria2-Integration](https://github.com/RossWang/Aria2-Integration) codes, thus solve the problem.

Also, this will break `Capture` > `Download Folder`, so this feature will be removed

- [x] #8
- [x] Bring back Capture Filter
    - [x] #9
    - [x] File Extensions
    - [x] Monitor Domains
    - [x] Ignore Domains
- [x] Remove `Capture` > `Download Folder`

**Comment by jc3213** [comment]
`Aria2-Integration` judge to capture downloads with response header `content-disposition` with `attachment`,  or `content-type` with `application`. Thus it can not handle with `Images`. That's a pity though

**Comment by jc3213** [comment]
Due to this change, Firefox's exclusive feature has been removed. File Size filter will be added in future

**Comment by jc3213** [comment]
@ivysrono 帮忙推一下[3.7.7](https://github.com/jc3213/download_with_aria2/releases/tag/3.7.7)（修改webRequest时抓到一个虫），顺便可以的话帮忙测试一下 [3.8.0b1](https://github.com/jc3213/download_with_aria2/releases/tag/3.8.0b1)

**Comment by git1-eipi10** [comment]
As I understand, we can not choose folder to save any more?

**Comment by jc3213** [comment]
> As I understand, we can not choose folder to save any more?

For Firefox - Yes

I can add a switch to let user determine which code to use, though.

**Comment by git1-eipi10** [comment]
I see. I know it would be much harder for you to maintain and improve the code if keeping both, but it's a really nice feature that I think no other aria2 add-ons have it. For me personally, it's also the most important feature that I decided to switch to this from other add-ons.

**Comment by jc3213** [comment]
I've bring back the `downloads` API code  in a rather crude way. If you'd like to use the downloads API code. You need to input
```javascript
Storage['capture_api'] = '0';
Storage['folder_mode'] = '0'; //'0' Default, '1' Browser, '2' Custom
Storage['folder_path'] = ''; //Your download folder path
chrome.storage.local.set(Storage);
```

**Comment by jc3213** [comment]
New UI for switch APIs and legacy options are available. this is a rather rough implement, but should work.

More improvement will be shipped, like i18n and channelled options

**Comment by git1-eipi10** [comment]
I've just tested version 3.10.0 on firefox but still can't see `Safe Mode`

![image](https://user-images.githubusercontent.com/97889040/151663000-42c40ea2-0830-40e1-87a3-149e2f0db04a.png)

**Comment by jc3213** [comment]
> I've just tested version 3.10.0 on firefox but still can't see `Safe Mode`
> 
> ![image](https://user-images.githubusercontent.com/97889040/151663000-42c40ea2-0830-40e1-87a3-149e2f0db04a.png)

It's in `about:addons` cause it will show a `confirm` window

**Comment by git1-eipi10** [comment]
Oh I see it now. Tks a lot 👍
