### ISSUE TITLE
some sites are not supported

### ISSUE THREAD

**Issue by cyberhardt** [jc3213/download_with_aria2#72]
I've noticed some sites aren't supported by the extension. I'm not sure what's causing this issue. Everything goes normally, but the download is a 14KB to 16KB HTML document instead of the actual file. some sites in which this happens are gofile.io and workupload.com, but I've also seen this happening in some other sites. 

the HTML document can be seen if you open the downloaded file as text. seems to be the underlying HTML of the webpage.

**Comment by jc3213** [comment]
It should be some kind of anti-leech protection, since the extension passes the `Cookies` and `Referer` correctly to aria2c

You can change the `User Agent`  and then try again. If your problem can't be fixed, I'm afraid maybe I can't fixed this on my side.

Can you provide me some urls for testing?

**Comment by cyberhardt** [comment]
my user agent is the default mozilla firefox one. I'll see if enabling Capture Web Request solves it

**Comment by cyberhardt** [comment]
I tried capturing web request and some other options such as Forward Request Headers, but none of them worked

**Comment by jc3213** [comment]
That's maybe the server doesn't support continuous download, or the download url is limited to be only accessed for 1 time by the server.

If you can provide other download manager programs that support these sites, I'll have a look into their browser extension source code to find the solution

**Comment by cyberhardt** [comment]
I'm not aware of any extension that works the same was as this one, so I'll close it as not planned for now
