### ISSUE TITLE
suggestion: add "open folder" button

### ISSUE THREAD

**Issue by cyberhardt** [jc3213/download_with_aria2#73]
I think it would be nice if there was an "open folder" button on a download box, for convenience. it could either open the download's location or the file itself.

**Comment by jc3213** [comment]
It is not allowed to open the local folder in a HTML/Javascript application by browser. I'm sorry that will not be an option

**Comment by cyberhardt** [comment]
> It is not allowed to open the local folder from an HTML/Javascript application. I'm sorry that will not be an option

oh, I didn't know that. sorry

**Comment by jc3213** [comment]
That's OK, and also, this is duplicated to #5
