### ISSUE TITLE
Can't continue an HTTP download, aria2 always rename and start a new download

### ISSUE THREAD

**Issue by escape0707** [jc3213/download_with_aria2#74]
Hi! Thanks for maintaining this extension till this day! I got another question today:

I want to download a large file from a file hosting website. I don't know the direct URL for the download, and that's why I want to use this extension's capture function. 

The download when through halfway and connection is aborted (as I expected). But when I click the button to restart the download hoping it continues from where it stopped, aria2 will always start a new download with a renamed file name (`xxxx(1).rar` for example) rather than continuing with the partial download.

The aria2-rpc command I'm using is: `aria2c --enable-rpc --rpc-secret=xxxx --file-allocation=none --continue --auto-file-renaming=false`

Did I miss any configuration or something?

Thanks in advance!

**Comment by jc3213** [comment]
Sorry for the late response, I don't have much time these days.

> The download when through halfway and connection is aborted (as I expected). But when I click the button to restart the download hoping it continues from where it stopped, aria2 will always start a new download with a renamed file name (xxxx(1).rar for example) rather than continuing with the partial download.

I wonder if  this is your problem

1. You've downloaded a large file from some file host with aria2c.exe
2. The download is stopped by the server, but you will like to continue the download
3. Then you clicked on `♻` button, but find aria2c.exe start a new download rather than continue the download?

If this is your problem, I'm afraid that I can't help you. The aria2c.exe json-rpc doesn't have any `aria2.xxxx` method to continue a download task that is `error`, or `removed`. Use `aria2.addUri`, and `aria2.removeDownloadResul` after `aria2.getOptions` and `aria2.getStatus` is my approach.

Maybe I should not call `aria2.removeDownloadResul` though.

You may try [Aria2 WebUI](https://ziahamza.github.io/webui-aria2/)
 and [AriaNG](https://aria2ng.github.io/). Please give me feedback if any of the two will work for you

**Comment by escape0707** [comment]
My first two steps are exactly what you've described, but for the third: I refreshed the file hosting page and restarted the download by clicking the download button again.

I believe [normally](https://aria2.github.io/manual/en/html/aria2c.html#resuming-download) if I start a download with aria2, then tried to use aria2 to download that again, I won't even need `--continue` or ` --auto-file-renaming false` to continue on previous download. But a renamed new download started when I used your extension.

**Comment by jc3213** [comment]
> My first two steps are exactly what you've described, but for the third: I refreshed the file hosting page and restarted the download by clicking the download button again.

This may because the download link and cookies are not the same, try turn off `Forward Request Headers`

**Comment by jc3213** [comment]
I wonder if your problem still persists? I can make some time this week to work on it though.

**Comment by escape0707** [comment]
Sorry, I was kind of busy in the past week, but I'll try to reproduce it in a minute.

**Comment by jc3213** [comment]
> Sorry, I was kind of busy in the past week, but I'll try to reproduce it in a minute.

You can try click the download url of the task to copy the download URL
     1. Click `⚙` of the task
     2. Scroll down to the `Download Urls` sections.
     3. Click the download url to copy

Then you can compare whether the download urls are the same

**Comment by escape0707** [comment]
I just tried it out again. Disabling the `Forward Request Headers` makes the download continues perfectly! Thanks! (Initially I wrote the wrong rpc Uri as simply `localhost` in the box and can't figure out why it doesn't work and after reboot of Firefox the config got emptied, until I reboot into my Linux system and compared against my old config 🤦 )

**Comment by jc3213** [comment]
Some hosts are checking for `Request Headers`, but some doesn't. 

For example, the host in #36 it won't download if `Forward Request Headers` is on. But most hosts, especially e-mail attachments are needed to turn the `FRH` on

Maybe I can add a ignore list as for `Capture Browser Downloads`. Then users will be much eaiser to deal with these "special sites"

**Comment by jc3213** [comment]
I've added `Exclude Domains for Headers` option to the extension, but I've also changed storage structure for new options. 

I've added the patch for the change for this change. but you may still met some trouble (cause I don't have time to test). You may have to restore your options to the default via the attachment
[downwitharia2_frh_exclude.json](https://github.com/jc3213/download_with_aria2/files/12889288/downwitharia2_frh_exclude.json)

@ivysrono @daiaji @wordpure

**Comment by jc3213** [comment]
Already release https://github.com/jc3213/download_with_aria2/releases/tag/4.5.0.2187, issue closed
