### ISSUE TITLE
2218Bug：Duplicate key

### ISSUE THREAD

**Issue by ivysrono** [jc3213/download_with_aria2#77]
Duplicate keys are not allowed in JSON files.

错误: Duplicate key: option_folder_enabled_title found in JSON
_locales/en/messages.json 第 200 行

Duplicate keys are not allowed in JSON files.

错误: Duplicate key: option_capture_always_title found in JSON
_locales/en/messages.json 第 236 行

Duplicate keys are not allowed in JSON files.

错误: Duplicate key: option_folder_enabled_title found in JSON
_locales/zh/messages.json 第 200 行

Duplicate keys are not allowed in JSON files.

错误: Duplicate key: option_capture_always_title found in JSON
_locales/zh/messages.json 第 236 行

**Comment by jc3213** [comment]
复制粘贴忘了改，好吧，我的。测试时间不太够

**Comment by jc3213** [comment]
2219修复了，顺便修复了option_folder_firefox打成了option_folder_forefox。
