### ISSUE TITLE
Changed image selector and preview logic | 调整了图像选择跟预览功能

### ISSUE THREAD

**Issue by jc3213** [jc3213/download_with_aria2#79]
- This change is for `Detected Images` window
- 本次修改针对`已探知图像`窗口

- Minimum all images to `84px*84px`
- 将所有图像都最缩放到`84像素x84像素`

- A new preview section
- 全新的预览区域

- Display a **full** preview when mouse over an image
- 当鼠标悬浮于图像时，预览区域显示**完整**预览

- Download | 下载
[images.zip](https://github.com/jc3213/download_with_aria2/files/13582744/images.zip)

- Preview | 预览
![test](https://github.com/jc3213/download_with_aria2/assets/8744936/934ad54c-8968-4aa9-b9c2-d44ca840eb22)

**Comment by jc3213** [comment]
@ivysrono @daiaji @wordpure 这个修改如何？

**Comment by jc3213** [comment]
今天用火狐做深度debug才发现之前为什么我没用`storage.sync`，就是因为火狐不支持，因为火狐的同步规则跟Chromium不一样，储存数据也要修改，我只能说没法子了。@ivysrono 目前最新版强行把`storage.sync`替换成了`storage.local`来工作。火狐用户估计从4.5.3开始就出错了。

**Comment by daiaji** [comment]
> 今天用火狐做深度debug才发现之前为什么我没用`storage.sync`，就是因为火狐不支持，因为火狐的同步规则跟Chromium不一样，储存数据也要修改，我只能说没法子了。@ivysrono 目前最新版强行把`storage.sync`替换成了`storage.local`来工作。火狐用户估计从4.5.3开始就出错了。

NAS出问题挺久了，aria2就没怎么用。
