### ISSUE TITLE
【BUG】最新版没办法保存更改，监视域名、例外域名了

### ISSUE THREAD

**Issue by RedDestiny** [jc3213/download_with_aria2#80]
我发现更新到最新版（v4.6.0），变得没办法保存更改，监视域名、例外域名的那几个设置了。

**Comment by jc3213** [comment]
Chromium测试正常，火狐的话因为中途改storage.sync导致了问题。同样的储存chrome.storage.sync就能正确储存，火狐就必定保存无法储存。导致中途好几个版本都有问题。4.6.0是修复了这个问题的，不过之前版本带来的错误已经发生了，你可能需要卸载扩展再重新安装。或者先导入默认设置用于修复

**Comment by RedDestiny** [comment]
> Chromium测试正常，火狐的话因为中途改`storage.sync`导致了问题。同样的储存`chrome.storage.sync`就能正确储存，火狐就必定报错无法储存。我也是之前才想起来为什么我一直在用`storage.local`储存数据。[#79 (comment)](https://github.com/jc3213/download_with_aria2/issues/79#issuecomment-1848898323)
> 
> 这个问题虽然最新版本修复了，但是之前的好几个版本都有问题。如果你是一路升级过来的，之前版本已经带来了错误，你可能需要卸载扩展再重新安装。或者导入一套默认设置用于修复

多谢。卸载重启火狐再安装就好了。

**Comment by jc3213** [comment]
问题解决就好了，火狐的文档我也看了，要求少于8KB，问题是哪怕储存`{"test": "test"}`都会报错，只能说无解
