### ISSUE TITLE
Is there an option to restore the default settings for the extension?

### ISSUE THREAD

**Issue by candrapersada** [jc3213/download_with_aria2#81]

**Comment by jc3213** [comment]
I‘m sorry there's not an option to restore the default settings for now. Here's some work around

- 1. Restore from background
    - 1. Turn on `Developer mode` on extentions manager
    - 2. Click on background of the extension
    - 3. Run javascript bellow
```javascript
    chrome.storage.sync.set(aria2Default);
```
- 2. Restore from pages
    - 1. Copy the declaration code for `aria2Default` from https://github.com/jc3213/download_with_aria2/blob/b4a4a4e5124eae5e2d0d6f86554fe422ad3c56a9/chromium/crossbrowser.js#L1
    - 2. Open `Options` or `Task Manager` or any other windows opened by this extension
    - 3. Press `F12` and open `Console`
    - 4. Paste and run declaration code for `aria2Default`
    - 5. Run javascript bellow
```javascript
    chrome.storage.sync.set(aria2Default);
```
