### ISSUE TITLE
Settings discarded/never saved

### ISSUE THREAD

**Issue by NotMithical** [jc3213/download_with_aria2#82]
I updated the extension today (v4.6.5.2366) and it immediately showed an error indicator. I checked the extensions settings and found that every field, most importantly those for the JSON-RPC hostname and secret, were blank. I re-entered the information and clicked save, but if I close close the tab and open the settings again everything I changed reverts to the default/empty settings.

**Comment by jc3213** [comment]
This maybe the update patch is not working correctly, you can copy and paste the code below into the debug consol, and press enter to run it. wait for 5 seconds and restart the extension, it will fix the problem
```javascript
        var uri = aria2Storage['jsonrpc_uri'];
        var secret = aria2Storage['jsonrpc_token'];
        if (uri !== undefined && secret !== undefined) {
            var {protocol, host} = new URL(uri);
            var scheme = protocol.slice(0, -1);
            aria2Storage['jsonrpc_scheme'] = scheme;
            aria2Storage['jsonrpc_host'] = host;
            delete aria2Storage['jsonrpc_uri'];
            aria2Storage['jsonrpc_secret'] = secret;
            delete aria2Storage['jsonrpc_token'];
            chrome.storage.sync.set(aria2Storage);
            aria2RPC = new Aria2(scheme, host, secret);
        }
```

**Comment by NotMithical** [comment]
Thank you, that's fixed that issue, however now when I attempt to start a download a new prompt opens as if I clicked the new DL button. I assume this is unrelated, should I open a separate issue?

**Comment by jc3213** [comment]
You should turn off `Enable Download Prompt` in options

**Comment by NotMithical** [comment]
That's taken care of it, thank you!
