### ISSUE TITLE
2373 error

### ISSUE THREAD

**Issue by ivysrono** [jc3213/download_with_aria2#83]
JavaScript syntax error (Parsing as module error: Unexpected token [ at line: 75 and column: 21) (Parsing as script error: Unexpected token [ at line: 75 and column: 21)

错误: There is a JavaScript syntax error in your code, which might be related to some experimental JavaScript features that aren't an official part of the language specification and therefore not supported yet. The validation cannot continue on this file.
crossbrowser.js 第 75 行，第 21 列

**Comment by jc3213** [comment]
试试2374，今天事情多，没仔细测试。看到 #82 的汇报就想重写一下兼容老版本的代码，复制粘贴的时候出错了。OTL

**Comment by jc3213** [comment]
最新的修改主要是为了能实时修改websocket跟http方案的使用。同时减少使用websocket的时候会新建多个websocket实例（后台的进度汇报啥的也会额外占用一个实例）
