### ISSUE TITLE
[Feature Request] 增加自定义RPC路径配置选项

### ISSUE THREAD

**Issue by kmou424** [jc3213/download_with_aria2#84]
如题，在服务器的场景下，为了安全性或其他原因，我们可能会反代aria2的rpc路径，从而使用其他路径（如`/`或`/anothoer_path`）等来连接。
提供自定义路径而不是写死为`/jsonrpc`会更具灵活性。希望可以增加此功能。
https://github.com/jc3213/download_with_aria2/blob/0f38d40ddbd70d0fa886a92aa64ab71242a8cb9b/chromium/libs/aria2.js#L10

**Comment by jc3213** [comment]
已经处理并做了对应补丁，只是补丁只会补上/jsonrpc，请后续自行修改为自己的地址
