### ISSUE TITLE
Firefox bug: 不抓取 sourceforge 下载

### ISSUE THREAD

**Issue by ivysrono** [jc3213/download_with_aria2#86]
已经开启抓取浏览器下载下的三个选项。
其他网站的抓取基本正常。
这个问题已经出现很久。
已经卸载扩展重装，依旧。

**Comment by jc3213** [comment]
![test1](https://github.com/jc3213/download_with_aria2/assets/8744936/d85a1717-0737-4262-a3b8-b88dcfe5d63c)
我测试正常啊？

**Comment by jc3213** [comment]
你排查一下规则啥的 https://github.com/jc3213/download_with_aria2/wiki/MatchPattern

**Comment by jc3213** [comment]
我发现了，是webRequest里面的错误，downloads API就没问题。我排查一下

**Comment by jc3213** [comment]
![bug1](https://github.com/jc3213/download_with_aria2/assets/8744936/0ca31de9-d2a5-4793-8b1c-cd4bbe99a05d)
发现错误了，我只有匹配的时候使用了`(name.toLowerCase() in aria2WebRequest)`，但是添加的时候还是result[name]，这样导致输入了`Content-Type`这种大写的，无法跟`content-type`进行匹配，因此boom了。

把这里修改成下面这样就可以修复了。
```javascript
    responseHeaders.forEach(({name, value}) => {
        name = name.toLowerCase();
        if (aria2WebRequest[name]) {
            result[name] = value;
        }
    });
```
![test3](https://github.com/jc3213/download_with_aria2/assets/8744936/7c648f0d-95ef-4d7f-9b9c-82fa8546db2d)
