### ISSUE TITLE
[BUG ?] 文件大小过滤无法生效

### ISSUE THREAD

**Issue by tooyangtoonaive** [jc3213/download_with_aria2#88]
extension version: 4.9.0.2629
browser version: firefox 115.8.0esr

describe:
1.勾选"启用下载弹框"，"启用捕获功能"，设置"监视文件后缀"为exe、zip，设置"文件大小"为100000
2.下载对应后缀的文件，例如 [QQ](https://im.qq.com/pcqq/index.shtml)
3.依然弹框，即便文件远小于100000MB

expect behaviour:
1.不弹框

**Comment by jc3213** [comment]
这是一个火狐浏览器本身的问题，在使用`downloads` API进行抓取时，无法获取文件大小`downloadItem.fileSize`，只有默认的-1（即未知），因此你必须启用`捕获网络请求`功能才能正常按文件大小捕获下载。

而根据`webRequest` API进行捕获的话，为了保证不会胡乱捕捉，此扩展只会审查`details.type`为`application/*`的url，因此无法对图片啥的实现捕获。

本身这是火狐自己的瑕疵，为了解决`downloads` API的缺陷，我特意参考 https://github.com/jc3213/download_with_aria2/issues/12 中提到的 [Aria2-Integration](https://github.com/RossWang/Aria2-Integration)，恕我无法解决这个问题。
