### ISSUE TITLE
[enhancement request] 扩充捕获下载过滤功能

### ISSUE THREAD

**Issue by tooyangtoonaive** [jc3213/download_with_aria2#89]
extension version: 4.9.0.2629
browser version: firefox 115.8.0esr

describe:
1."监视文件后缀"只能指定后缀，无法设置为任意后缀。
2.勾选"总是捕获下载"，缺少针对文件大小的例外。
3."例外域名"可否支持正则表达式？

**Comment by jc3213** [comment]
关于1，因为这个扩展是根据另一个扩展改过来的，我参考了FDM之类的软件，然后根据自己日常使用发现，你提出的指定`任意后缀`可以通过总是捕获下载实现。
关于2，这个我确实没考虑到，原因基本同上，这个需求相对来说比较稀少，但是理论上是可以添加进来的。
关于3，实际匹配的时候使用了正则表达式，你在使用中其实是可以用`www.abc*.com`这类的用法的。

**Comment by jc3213** [comment]
可以下载 https://github.com/jc3213/download_with_aria2/releases/tag/4.10.0

@ivysrono 虽然是pre-release版本，因为这个版本为了此issue的功能修改了储存的键

**Comment by jc3213** [comment]
你试试手动把4.10.0.0000改成4.10.0呢？至于action.onClicked我在background里做了`action = browserAction`，不应该出问题吧？之前也是这么做的。
