### ISSUE TITLE
[enhancement request] 手动刷新 aria2 rpc 服务器

### ISSUE THREAD

**Issue by detiam** [jc3213/download_with_aria2#90]
我用 motrix 作为 aria2 服务器使用，有些时候打开了浏览器但是没打开 motrix ，这个插件就会有个红色的 `E` 在插件图标右上角（我用的 firefox），这时再启动motrix。插件可以捕获下载但点击下载按钮 motrix 没反应，需要重启浏览器恢复正常。

**Comment by jc3213** [comment]
我有设置当aria2的json-rpc连接失败时每x秒（根据你设置的刷新manager的频率）尝试重新连接，似乎这个功能并没有正常工作？

你要手动刷新json-rpc的连接，需要修改json-rpc的url部分，然后再改回来。至于重连功能则需要更多的测试了。

**Comment by jc3213** [comment]
我修改了`libs/aria2.js`跟`crossbrowser.js`，从而实现了不管用户是否开启json-rpc，都能对其进行检测。即使中途用户关闭json-rpc再重开，理论上也能正常检查了。
