### ISSUE TITLE
bug：下载完成后工具栏角标不 -1

### ISSUE THREAD

**Issue by ivysrono** [jc3213/download_with_aria2#91]
Firefox 浏览器和扩展都是最新版。

大约就是从 4.10.0 开始，角标数量只增不减。

**Comment by jc3213** [comment]
我自己测试一切正常，唯一有问题的版本是 [4.10.0.2669](https://github.com/jc3213/download_with_aria2/releases/tag/4.10.0.2669)。我自己测试一切正常。你可以考虑试试禁用扩展再重新启用试试？

**Comment by jc3213** [comment]
这里是录像 https://we.tl/t-BTfYsjOBhu
