### ISSUE TITLE
Onedrive 无法获取下载文件

### ISSUE THREAD

**Issue by caite425** [jc3213/download_with_aria2#94]
作者您好，能够找到一款持续更新的火狐的插件真是太不容易了，首先表达感谢。
使用过程中，其他网盘都没有问题，就是onedrive无法获取文件的大小，也没法开始下载
![image](https://github.com/jc3213/download_with_aria2/assets/98703352/11a2591a-95d5-4418-991d-fb5d31473688)
![image](https://github.com/jc3213/download_with_aria2/assets/98703352/cdf32bfc-2959-478f-8864-b6a145807d6d)
9GB的文件，但是始终无法获取大小，设置里的file-allocation是trunc模式，也试过其他的，也都不行
使用的是2694的版本。

**Comment by jc3213** [comment]
可以得话你把地址发我试试？我想知道是哪一个步骤出错了，你用了哪一个抓取方案？如果普通方案出错，推荐你打开`捕获网络请求`这个设置。

**Comment by caite425** [comment]
![image](https://github.com/jc3213/download_with_aria2/assets/98703352/935d0260-ac85-4396-be81-470b78919cf6)
![image](https://github.com/jc3213/download_with_aria2/assets/98703352/20ab67e9-419f-4e18-8b9a-77ee80e8693f)

没有问题了，加了个头竟然就可以下载了！之前默认的trasmission 4.0反倒不行，非常感谢！

**Comment by jc3213** [comment]
短时间内测试不了，提示太多人访问需要等待
![1](https://github.com/jc3213/download_with_aria2/assets/8744936/f39e6508-d79f-493d-b51c-1227632c77a8)

**Comment by caite425** [comment]
![image](https://github.com/jc3213/download_with_aria2/assets/98703352/c79b3a6c-8313-48d2-94ef-ddae8b4d93c0)
非常感谢详细解答，我看了下确实是如您所说，拦截的话确实就是先取消下载再发送到aria2，等同于就是下载了两次吧，流量直接超标了。等过个24小时我再添加捕获网络请求看一下，如果是捕获的话，那么火狐自带的下载器还会开始下载吗？

**Comment by jc3213** [comment]
根据我自己的观察，`webRequest.onHeaderRecieved`事件是比`downloads`还提前触发的，在触发后会直接进行`return {cancel: true}`进行`webRequestBlocking`。但是这里又涉及到文件种类，因此我参考 #12 导入的[Aria2-Integration](https://github.com/RossWang/Aria2-Integration) 。源码就是请求头content-type="application/xxxx"或者存在content-disposition就会抓取，因此特定的类型可能不会被抓取。

而且我估计哪怕是Chrome这边使用`downloads`，虽然不会开始下载，但是也是触发了下载进程的，也会出现这个问题。如果可以的话，你可以试试右键菜单，或者通过别的手段提取下载链接但是不主动点击，避免使用Quota。通过 [Wiki: Message](https://github.com/jc3213/download_with_aria2/wiki/Message) 通道传递给扩展。options部分可以用`{referer: location.href, header: ['Cookie: ' + document.cookie], out: '文件名', dir: '保存位置'}`

**Comment by jc3213** [comment]
你可以试试下面的代码，因为我测试无法通过document.cookie来获取当前的cookie，你可能需要别的扩展来获取，并且修改成`['Cookie: cookieName1=cookieValue1; cookieName2=cookieValue2;']` 这种格式，然后赋值给 header。

```javascript
const form = document.querySelector('#download-form');
const file = document.querySelector('.uc-name-size > a');
const search = [...new FormData(form)].map((value, key) => key + '=' + value);
const url = form.getAttribute('action') + '?' + search.join('&');
const options = {referer: location.href, out: file.textContent};
window.postMessage({ aria2c: 'aria2c_jsonrpc_call', params: { urls: [ {url, options} ] }, source: 'call' });
```

**Comment by caite425** [comment]
![image](https://github.com/jc3213/download_with_aria2/assets/98703352/876f1b36-776d-4b3c-bcd4-8bdae7de66cf)
我现在测试了一下，开启了捕获请求，这次自带的下载器并没有启动，而是直接被拦截了，可以正常下载。
不过第二次下载的时候又提示没流量了。。再次获得2KB的文件，又得明天测试了。明天试一下关闭捕获请求看一下。
不过代码这方面不是很懂。。单纯就是个普通用户而已，非常感谢大佬的热心帮助

**Comment by jc3213** [comment]
onedrive会下载两次的原因我不太清楚，也许跟跳转或自动重试有关？你可以提供一个onedrive下载让我测试以下，我看看能不能修复？不需要太大的文件，我就是看看触发2次下载时的webRequest里的记录。

当然，你也可以通过aria2 jsonrpc管理器看看下载任务的链接，看看是不是不一样，如果不一样就是涉及到跳转跟重试，这个估计没办法解决？
