### ISSUE TITLE
希望可以添加多个rpc服务器

### ISSUE THREAD

**Issue by lolo77777** [jc3213/download_with_aria2#95]
firefox上好用的aria2扩展太少了，现在很好用，非常感谢作者的幸苦付出
希望可以添加管理多个rpc服务器，这样可以在本机传输到远程rpc server进行下载

**Comment by jc3213** [comment]
我当时有做个实验版本，不过因为牵扯太多东西，当时只做了右键菜单，任务栏切换档案，但是核心的功能没怎么修改。

现在扩展功能很多比如抓取浏览器下载啥的，这些设置是否跟随多RPC变化，优先级怎么设置，以及后台的运行信息啥的如何控制，各个下载页面新增筛选功能啥的。

如果不是扩展层面的要求多RPC，那么我更推荐使用其他支持多RPC的Web UI来代替扩展的任务管理器
