### ISSUE TITLE
例外域名样式缺陷

### ISSUE THREAD

**Issue by ivysrono** [jc3213/download_with_aria2#99]
如果例外域名中存在特殊符号如 `-`，域名本身再长一点，就很容易在`-`处断行，看不到后续部分。

如`riot-optimizer.com`

其实本扩展仅适用于桌面版，这种显示可以大方一点不用弄得这么局促。

**Comment by jc3213** [comment]
我想知道是显示缺陷还是功能缺陷？如果是显示缺陷的话能给我一张图让我看看你期望的效果吗？

**Comment by jc3213** [comment]
这个应该是css里面word-break相关的东西吧。我回头研究下看看。

**Comment by jc3213** [comment]
这下应该没问题了吧，相关设置是`{white-space: nowrap;}`

**Comment by jc3213** [comment]
一行改成3个了，2个实在太少了……

**Comment by jc3213** [comment]
我当时做了个分支版本，整合`webRequest`给chrome manifest v2用。可能那会出问题了，我重新用火狐debug一下
